# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               "琴之音 Words Worlds"
tagline:             '「一沙一世界 一叶一天堂」'
description:         'Love all，trust a few，do wrong to none'
url:                 http://biqin.me/
baseurl:             http://biqin.me/
paginate:            6
excerpt_separator:   ""

# About/contact
author:
  name:              Rebecca Lee
  email:             rebeccabfsu20@gmail.com

# Data
gavatar: ./public/Rebecca.png
favicon: ./public/Becky.png

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : Rebecca
  disqus :
      short_name : Rebecca
  # ...
  
# Custom vars
version:             1.0.0
