# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               "Microdust 微尘"
tagline:             '「在遙遠的地方 一切虔誠終必相遇」'
description:         '明朝即長路 惜取此時心'
url:                 http://azeril.me/
baseurl:             http://azeril.me/
paginate:            7
excerpt_separator:   ""

# About/contact
author:
  name:              Azeril
  url:               https://azeril.me/
  email:             azeril@live.cn

comments :
  provider : duoshuo
  duoshuo :
    short_name : Azeril
  disqus :
      short_name : Azeril
  # ...
  
# Custom vars
version:             1.0.0
