# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               "Public"
tagline:             'Notes'
description:         ''
url:                 http://krassik.github.io
baseurl:             /
paginate:            5
excerpt_separator:   ""

# About/contact
author:
  name:              krassik
  url:               https://krassik.github.io
  email:             krassimir.krustev@gmail.com

# Custom vars
version:             1.0.0
