# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               "Microdust"
tagline:             '微尘'
description:         ''
url:                 http://azeril.me/
baseurl:             /
paginate:            7
excerpt_separator:   ""

# About/contact
author:
  name:              Azeril
  url:               https://azeril.me/
  email:             azeril@live.cn

# Custom vars
version:             1.0.0
