# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               "Microdust"
tagline:             '微尘'
description:         '爱与希望'
url:                 http://azeril.me/
baseurl:             /
paginate:            5
excerpt_separator:   ""

# About/contact
author:
  name:              krassik
  url:               https://azeril.me/
  email:             krassimir.krustev@gmail.com

# Custom vars
version:             1.0.0
