# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               "琴之音 Words Worlds"
tagline:             '「To see a world in a grain of sand And a heaven in a wild flower」'
description:         'Love all，trust a few，do wrong to none'
url:                 http://biqin.me/
baseurl:             http://biqin.me/
paginate:            7
excerpt_separator:   ""

# About/contact
author:
  name:              Rebecca
  email:             rebeccabfsu20@gmail.com

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: ./public/favicon.png

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : Rebecca
  disqus :
      short_name : Rebecca
  # ...
  
# Custom vars
version:             1.0.0
